### ISSUE TITLE
Bug: Harvester

### ISSUE THREAD

**Issue by Phreeman703** [MoonManModding/EmergingTechnology#97]
Hi, i have a bug, when setup a harverster.

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.239.jar)
  iceandfire (iceandfire_1.12.2_1.8.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.72-core.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 5/5/20 2:30 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at io.moonman.emergingtechnology.machines.harvester.HarvesterTileEntity.isIdle(HarvesterTileEntity.java:447)
	at io.moonman.emergingtechnology.machines.harvester.HarvesterTileEntity.cycle(HarvesterTileEntity.java:201)
	at io.moonman.emergingtechnology.machines.MachineTileBase.func_73660_a(MachineTileBase.java:38)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by MoonManModding** [comment]
Hi,

Thanks for the bug report!

Which version of Emerging Technology are you using? I believe this bug is from an older release, so updating to latest should resolve the issue.

Cheers

**Comment by Phreeman703** [comment]
Hi,

Yap, i used to old version 1.3.9-beta.

**Comment by MoonManModding** [comment]
Hi,

Unfortunately the bug is in that version. Please make a backup of your world and also as a precaution break and replace any harvester machines before updating 😁

Thanks!
